package ca.arnaud.hopsboilingtimer.app.extension

// Generated by ChatGPT
fun String.expandTemplate(vararg args: String): String {
    var result = this
    args.forEachIndexed { index, value ->
        result = result.replace("^${index + 1}", value)
    }
    return result
}